### ISSUE TITLE
Show which object properties are required or not by default

### ISSUE THREAD

**Issue by durey** [sbrunner/jsonschema2md2#12]
Would not be amazing to show which object properties are required or not in the generated Markdown?

So this schema:

```
type: object
required:
  - colours
additionalProperties: false
properties:
  colours:
    [...]
  numbers:
    [...]
```

would generate a different Markdown than this schema:

```
type: object
required:
  - colours
  - numbers
additionalProperties: false
properties:
  colours:
    [...]
  numbers:
    [...]
```

Currently, `additionalProperties` is taken into account, but `required` is ignored AFAIK.
